//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.24 at 10:10:01 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.electronichealth.net.au/smd/xsd/Message/2010", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.net.electronichealth.ns.smd.message.v2010;
